apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-flask-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-flask
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
